---

apache_packages:
  - apache2
  - apache2-utils

apache_mods_enabled:
  - rewrite.load

# Configuration of Apache in Ubuntu 18.04
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2

# Configurations
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"


apache_listen_ip: "*"
apache_listen_port: 80

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  - servername: "local.dev"
    documentroot: "/var/www/wordpress"
    #documentroot: "{{ webserver_root }}"

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymlinks"

