---

- name: Install unzip package
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Check if Wordpress has been previously downloaded
  stat:
    path: "{{ wp_download_path }}"
  register: wp_zipped

- name: Download Wordpress
  get_url:
    url: "{{ wp_url }}"
    dest: "{{ wp_download_path }}"
  when: wp_zipped.stat.exists == False

- name: Unzip Wordpress
  unarchive:
    src: "{{ wp_download_path }}"
    dest: "{{ wp_webserver_path }}"
    copy: no

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wp_webserver_path }}/wp-config.php"

