---

mysql_packages:
  - python-selinux
  - mysql-server
  - python-mysqldb

mysql_service: mysql

mysql_conf_dir: "/etc/mysql"

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
#mysql_bind_address: "192.168.33.12,192.168.33.13"
mysql_root_db_pass: root

mysql_db:
  - name: wordpressdb

mysql_users:
  - name: wpuser
    pass: wppass
    priv: "*.*:ALL"

