---

php_packages:
  - php7.2
  - libapache2-mod-php7.2
  - php7.2-mysql
  - php7.2-curl
  - php7.2-gd
  - php7.2-intl
  - php-pear
  - php-imagick
  - php7.2-imap
#  - php7.2-mcrypt
  - php-memcache
  - php7.2-pspell
  - php7.2-recode
  - php7.2-sqlite3
  - php7.2-tidy
  - php7.2-xmlrpc
  - php7.2-xsl
  - php7.2-mbstring
  - php-gettext
  - php7.2-opcache
  - php-apcu
